artifact_location: file:///Users/meuralnetwork/Projects/assignment/mlruns/952293898453491715
creation_time: 1745549575969
experiment_id: '952293898453491715'
last_update_time: 1745549575969
lifecycle_stage: active
name: Cancer Detection Experiments
