apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: cancer-classifier
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      storageUri: "pvc://mlflow-models/cancer-classifier" # Using PVC instead of S3
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"
      env:
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow-server:5000"
        - name: MODEL_NAME
          value: "cancer-classifier"
