apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlflow-models
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  selector:
    app: mlflow-server
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
        - name: mlflow-server
          image: mlflow/mlflow:latest
          ports:
            - containerPort: 5000
          command:
            [
              "mlflow",
              "server",
              "--host",
              "0.0.0.0",
              "--port",
              "5000",
              "--backend-store-uri",
              "sqlite:///mlflow.db",
              "--default-artifact-root",
              "./mlruns",
            ]
          volumeMounts:
            - name: mlflow-models
              mountPath: ./mlruns
          env:
            - name: MLFLOW_TRACKING_URI
              value: "http://0.0.0.0:5000"
            - name: MLFLOW_ARTIFACT_ROOT
              value: "./mlruns"
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      volumes:
        - name: mlflow-models
          persistentVolumeClaim:
            claimName: mlflow-models
